### ISSUE TITLE
TypeError: Cannot read property 'password' of null

### ISSUE THREAD

**Issue by paulomcnally** [nodenica/nodenica-website#22]
TypeError: Cannot read property 'password' of null
    at Promise.<anonymous> (/app/models/users.js:91:21)
    at Promise.<anonymous> (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:171:8)
    at emitOne (events.js:77:13)
    at Promise.emit (events.js:169:7)
    at Promise.emit (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:88:38)
    at Promise.fulfill (/app/node_modules/mongoose/node_modules/mpromise/lib/promise.js:101:20)
    at Immediate.cb (/app/node_modules/mongoose/lib/query.js:1138:30)
    at Immediate._onImmediate (/app/node_modules/mongoose/node_modules/mquery/lib/utils.js:126:16)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by paulomcnally** [comment]
@christopher-ramirez se me hace que esto me llego por el merge de ayer.

:)
